### PR TITLE
Single exe build

### PR DESCRIPTION
**Pull request by 0blu**
- DotNet 6
- Renamed config file to `HermesProxy.config`
- Config file is required (otherwise app will exit)
- Embedded `BNetServer.pfx`
- No hard framework when building it yourself (you may want to delete the `bin` folder after merge)
- Much easier output folder structure
- Single executable build 🎉 So that inexperienced users don't have to search for the `HermesProxy.exe` in all those files

image

### CODE REVIEW

**Comment by 0blu** [comment]
We _could_ also embed all the CSV files

**Comment by ratkosrb** [comment]
If you embed the CSV files then users can no longer edit them. Currently it allows you to customize items through hotfixes for example.

**Comment by MaxtorCoder** [comment]
Looks good to me 👀 @ratkosrb are you able to move to VS2022 yet?

**Comment by ratkosrb** [comment]
I have not installed it, but i can simply revert this commit on my fork when compiling if you insist on it.

**Comment by MaxtorCoder** [comment]
> I have not installed it, but i can simply revert this commit on my fork when compiling if you insist on it.

I mean I would love for everyone to be on the same version here 😄

**Comment by insunaa** [comment]
Tested and confirmed to work on Linux as well :+1:

**Comment by celguar** [comment]
why remove default config and require file. that way we no longer can start app without config file but with command line parameters. e.g. have 2 shortcuts for vanilla/tbc instead of having to edit config every time. or am i wrong

**Comment by 0blu** [comment]
Hmm, good point. I will revert the requirement.

**Comment by celguar** [comment]
> Hmm, good point. I will revert the requirement.

I'm sorry I guess I was wrong. Having no config makes no sense after all.

**Comment by celguar** [comment]
Thanks for update :)

**Pull request merged**
