### PR TITLE
 Fix the character freeze issue after hunter eyes of the beast

### PR DESCRIPTION
**Pull request by 7upcat**
Adding workaround logic prevent freeze issue after hunter  'Eyes of the Beast' .

### CODE REVIEW

**Comment by ratkosrb** [comment]
How can sending empty update object fix anything?

**Comment by 7upcat** [comment]
this fix is ref  the workaroud for mind vision and mind control ,and i test it can work fine.

https://github.com/WowLegacyCore/HermesProxy/blob/0bd883f2c9085868d4564ea84b96aa45edb06077/HermesProxy/World/Client/PacketHandlers/UpdateHandler.cs#L104

**Comment by 7upcat** [comment]
@ratkosrb as discussion refactor the code and submit a temporary fix.

**Comment by 7upcat** [comment]
Yes, done for that.

**Pull request closed without merging**
